module ReturnCode
  S_OK = 'S_OK'             #操作成功
  S_INACTIVE_OK = 'S_INACTIVE_OK' #特指未激活用户登陆成功
  FA_INVALID_PARAMETERS = 'FA_INVALID_PARAMETERS' #请求参数非法，一般指某必须参数为空或取值非法
  FA_NOT_SUPPORTED_PARAMETERS = 'FA_NOT_SUPPORTED_PARAMETERS' #请求参数不支持，一般指某参数取值合法，但不支持取该值
  FA_UNAUTHORIZED = 'FA_UNAUTHORIZED'  #用户权限不足
  FA_UNKNOWN_ERROR = 'FA_UNKNOWN_ERROR'   #未知错误
  FA_USER_ALREADY_EXIT = 'FA_USER_ALREADY_EXIT'              #注册时，用户已经存在
  FA_USER_NOT_EXIT = 'FA_USER_NOT_EXIT'   #登录时，用户(账号)不存在
  FA_PASSWORD_ERROR = 'FA_PASSWORD_ERROR' #登陆时或修改时，当前密码错误
  FA_PASSWORD_INCONSISTENT = 'FA_PASSWORD_INCONSISTENT' #新密码与确认密码不一致
  FA_SESSION_HAS_BEEN_CREATED = 'FA_SESSION_HAS_BEEN_CREATED'  #SESSION已被创建，可能是同一客户端重复登陆
  FA_SMTP_AUTHENTICATION_ERROR = 'FA_SMTP_AUTHENTICATION_ERROR'    #Devise　SMTP登陆认证失败
  FA_INNER_NET_CONNECT_ERROR = 'FA_INNER_NET_CONNECT_ERROR' #内部网络连接错误，可能是sunspot:solr等服务器未启动
  FA_TERM_ALREADY_EXIT = 'FA_TERM_ALREADY_EXIT'  #条目已经存在，一般指用户新建某条目时，该条目已有同名存在
end