defaults: &defaults
  cache:
    uploaded_avatar_experied_minute: 10
    automatch_terms_experied_minute: 60
  upload_url: "http://zrquan.qiniudn.com/"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults