defaults: &defaults
  cache:
    #手机验证码的有效时间
    verify_code_experied_minute: 30
    uploaded_avatar_experied_minute: 10
    #自动匹配的预处理数据的缓存有效时间
    automatch_terms_experied_minute: 60
  upload_url: "http://zrquan.qiniudn.com/"
#  配置问答提问时显示的热门主题,key为theme id, value为theme name
  hot_themes:
    1: "毕业生求职"
    2: "跳槽"
    3: "简历修改"
    4: "找实习"
    5: "面试咨询"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults